[package]
name = "gb"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = "0.27"
strum_macros = "0.27.2"
paste = "1.0"
sdl2 = { version = "0.38" }
image = "0.25"
itertools = "0.14"
fontdue = "0.7.3"